export type Operacion = {
  id: string
  fecha: Date
  tipo: "billar" | "juegos" | "solo-consumo"
  mesa?: string
  tipoMesa?: "billar" | "juegos"
  metodoPago: "efectivo" | "tarjeta" | "transferencia" | "mixto"
  usuario: string
  productos: { nombre: string; cantidad: number; precio: number }[]
  ingresoJuego: number
  ingresoConsumos: number
  total: number
  descuento: number
  estado: "abierta" | "cerrada"
}

function getDate(daysAgo: number): Date {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  date.setHours(12, 0, 0, 0)
  return date
}

const OPERACIONES_FIXTAS: Operacion[] = [
  {
    id: "OP-001",
    fecha: getDate(0),
    tipo: "billar",
    mesa: "Mesa 1",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Juan Pérez",
    productos: [
      { nombre: "Coca Cola", cantidad: 2, precio: 8 },
      { nombre: "Nachos", cantidad: 1, precio: 25 },
    ],
    ingresoJuego: 75,
    ingresoConsumos: 41,
    descuento: 0,
    total: 116,
    estado: "cerrada",
  },
  {
    id: "OP-002",
    fecha: getDate(0),
    tipo: "billar",
    mesa: "Mesa 2",
    tipoMesa: "billar",
    metodoPago: "tarjeta",
    usuario: "María López",
    productos: [
      { nombre: "Cerveza", cantidad: 3, precio: 12 },
      { nombre: "Hamburguesa", cantidad: 2, precio: 25 },
    ],
    ingresoJuego: 90,
    ingresoConsumos: 86,
    descuento: 10,
    total: 166,
    estado: "cerrada",
  },
  {
    id: "OP-003",
    fecha: getDate(0),
    tipo: "billar",
    mesa: "Mesa 3",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Carlos Gómez",
    productos: [{ nombre: "Agua", cantidad: 2, precio: 4 }],
    ingresoJuego: 60,
    ingresoConsumos: 8,
    descuento: 0,
    total: 68,
    estado: "abierta",
  },
  {
    id: "OP-004",
    fecha: getDate(0),
    tipo: "juegos",
    mesa: "Mesa 6",
    tipoMesa: "juegos",
    metodoPago: "transferencia",
    usuario: "Ana Martínez",
    productos: [
      { nombre: "Coca Cola", cantidad: 4, precio: 8 },
      { nombre: "Nachos", cantidad: 2, precio: 25 },
    ],
    ingresoJuego: 80,
    ingresoConsumos: 82,
    descuento: 0,
    total: 162,
    estado: "cerrada",
  },
  {
    id: "OP-005",
    fecha: getDate(0),
    tipo: "juegos",
    mesa: "Mesa 7",
    tipoMesa: "juegos",
    metodoPago: "mixto",
    usuario: "Juan Pérez",
    productos: [{ nombre: "Cerveza", cantidad: 2, precio: 12.5 }],
    ingresoJuego: 70,
    ingresoConsumos: 25,
    descuento: 5,
    total: 90,
    estado: "cerrada",
  },
  {
    id: "OP-006",
    fecha: getDate(0),
    tipo: "solo-consumo",
    metodoPago: "efectivo",
    usuario: "María López",
    productos: [
      { nombre: "Hamburguesa", cantidad: 1, precio: 25 },
      { nombre: "Coca Cola", cantidad: 1, precio: 8 },
    ],
    ingresoJuego: 0,
    ingresoConsumos: 33,
    descuento: 0,
    total: 33,
    estado: "cerrada",
  },
  {
    id: "OP-007",
    fecha: getDate(1),
    tipo: "billar",
    mesa: "Mesa 1",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Carlos Gómez",
    productos: [
      { nombre: "Cerveza", cantidad: 4, precio: 12 },
      { nombre: "Nachos", cantidad: 1, precio: 25 },
    ],
    ingresoJuego: 85,
    ingresoConsumos: 73,
    descuento: 8,
    total: 150,
    estado: "cerrada",
  },
  {
    id: "OP-008",
    fecha: getDate(1),
    tipo: "juegos",
    mesa: "Mesa 8",
    tipoMesa: "juegos",
    metodoPago: "tarjeta",
    usuario: "Ana Martínez",
    productos: [{ nombre: "Agua", cantidad: 3, precio: 4 }],
    ingresoJuego: 65,
    ingresoConsumos: 12,
    descuento: 0,
    total: 77,
    estado: "cerrada",
  },
  {
    id: "OP-009",
    fecha: getDate(1),
    tipo: "solo-consumo",
    metodoPago: "efectivo",
    usuario: "Juan Pérez",
    productos: [
      { nombre: "Hamburguesa", cantidad: 2, precio: 25 },
      { nombre: "Cerveza", cantidad: 2, precio: 12 },
    ],
    ingresoJuego: 0,
    ingresoConsumos: 74,
    descuento: 0,
    total: 74,
    estado: "cerrada",
  },
  {
    id: "OP-010",
    fecha: getDate(1),
    tipo: "billar",
    mesa: "Mesa 4",
    tipoMesa: "billar",
    metodoPago: "transferencia",
    usuario: "María López",
    productos: [{ nombre: "Coca Cola", cantidad: 1, precio: 8 }],
    ingresoJuego: 55,
    ingresoConsumos: 8,
    descuento: 0,
    total: 63,
    estado: "abierta",
  },
  {
    id: "OP-011",
    fecha: getDate(2),
    tipo: "billar",
    mesa: "Mesa 2",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Carlos Gómez",
    productos: [
      { nombre: "Nachos", cantidad: 2, precio: 25 },
      { nombre: "Cerveza", cantidad: 3, precio: 12 },
    ],
    ingresoJuego: 95,
    ingresoConsumos: 86,
    descuento: 0,
    total: 181,
    estado: "cerrada",
  },
  {
    id: "OP-012",
    fecha: getDate(2),
    tipo: "juegos",
    mesa: "Mesa 6",
    tipoMesa: "juegos",
    metodoPago: "tarjeta",
    usuario: "Ana Martínez",
    productos: [
      { nombre: "Coca Cola", cantidad: 2, precio: 8 },
      { nombre: "Agua", cantidad: 1, precio: 4 },
    ],
    ingresoJuego: 72,
    ingresoConsumos: 20,
    descuento: 0,
    total: 92,
    estado: "cerrada",
  },
  {
    id: "OP-013",
    fecha: getDate(3),
    tipo: "billar",
    mesa: "Mesa 3",
    tipoMesa: "billar",
    metodoPago: "mixto",
    usuario: "Juan Pérez",
    productos: [{ nombre: "Hamburguesa", cantidad: 1, precio: 25 }],
    ingresoJuego: 80,
    ingresoConsumos: 25,
    descuento: 5,
    total: 100,
    estado: "cerrada",
  },
  {
    id: "OP-014",
    fecha: getDate(3),
    tipo: "solo-consumo",
    metodoPago: "efectivo",
    usuario: "María López",
    productos: [
      { nombre: "Cerveza", cantidad: 5, precio: 12 },
      { nombre: "Nachos", cantidad: 3, precio: 25 },
    ],
    ingresoJuego: 0,
    ingresoConsumos: 135,
    descuento: 10,
    total: 125,
    estado: "cerrada",
  },
  {
    id: "OP-015",
    fecha: getDate(5),
    tipo: "juegos",
    mesa: "Mesa 7",
    tipoMesa: "juegos",
    metodoPago: "tarjeta",
    usuario: "Carlos Gómez",
    productos: [
      { nombre: "Coca Cola", cantidad: 3, precio: 8 },
      { nombre: "Hamburguesa", cantidad: 1, precio: 25 },
    ],
    ingresoJuego: 68,
    ingresoConsumos: 49,
    descuento: 0,
    total: 117,
    estado: "cerrada",
  },
  {
    id: "OP-016",
    fecha: getDate(5),
    tipo: "billar",
    mesa: "Mesa 1",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Ana Martínez",
    productos: [{ nombre: "Agua", cantidad: 4, precio: 4 }],
    ingresoJuego: 88,
    ingresoConsumos: 16,
    descuento: 0,
    total: 104,
    estado: "cerrada",
  },
  {
    id: "OP-017",
    fecha: getDate(7),
    tipo: "billar",
    mesa: "Mesa 5",
    tipoMesa: "billar",
    metodoPago: "transferencia",
    usuario: "Juan Pérez",
    productos: [
      { nombre: "Cerveza", cantidad: 2, precio: 12 },
      { nombre: "Nachos", cantidad: 1, precio: 25 },
    ],
    ingresoJuego: 92,
    ingresoConsumos: 49,
    descuento: 0,
    total: 141,
    estado: "cerrada",
  },
  {
    id: "OP-018",
    fecha: getDate(7),
    tipo: "solo-consumo",
    metodoPago: "efectivo",
    usuario: "María López",
    productos: [{ nombre: "Hamburguesa", cantidad: 3, precio: 25 }],
    ingresoJuego: 0,
    ingresoConsumos: 75,
    descuento: 0,
    total: 75,
    estado: "cerrada",
  },
  {
    id: "OP-019",
    fecha: getDate(10),
    tipo: "juegos",
    mesa: "Mesa 8",
    tipoMesa: "juegos",
    metodoPago: "tarjeta",
    usuario: "Carlos Gómez",
    productos: [
      { nombre: "Coca Cola", cantidad: 5, precio: 8 },
      { nombre: "Cerveza", cantidad: 2, precio: 12 },
    ],
    ingresoJuego: 75,
    ingresoConsumos: 64,
    descuento: 0,
    total: 139,
    estado: "cerrada",
  },
  {
    id: "OP-020",
    fecha: getDate(10),
    tipo: "billar",
    mesa: "Mesa 2",
    tipoMesa: "billar",
    metodoPago: "mixto",
    usuario: "Ana Martínez",
    productos: [
      { nombre: "Nachos", cantidad: 1, precio: 25 },
      { nombre: "Agua", cantidad: 2, precio: 4 },
    ],
    ingresoJuego: 83,
    ingresoConsumos: 33,
    descuento: 6,
    total: 110,
    estado: "cerrada",
  },
  {
    id: "OP-021",
    fecha: getDate(14),
    tipo: "billar",
    mesa: "Mesa 4",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Juan Pérez",
    productos: [
      { nombre: "Hamburguesa", cantidad: 2, precio: 25 },
      { nombre: "Cerveza", cantidad: 4, precio: 12 },
    ],
    ingresoJuego: 78,
    ingresoConsumos: 98,
    descuento: 0,
    total: 176,
    estado: "cerrada",
  },
  {
    id: "OP-022",
    fecha: getDate(14),
    tipo: "solo-consumo",
    metodoPago: "tarjeta",
    usuario: "María López",
    productos: [
      { nombre: "Coca Cola", cantidad: 6, precio: 8 },
      { nombre: "Nachos", cantidad: 2, precio: 25 },
    ],
    ingresoJuego: 0,
    ingresoConsumos: 98,
    descuento: 0,
    total: 98,
    estado: "cerrada",
  },
  {
    id: "OP-023",
    fecha: getDate(20),
    tipo: "juegos",
    mesa: "Mesa 6",
    tipoMesa: "juegos",
    metodoPago: "efectivo",
    usuario: "Carlos Gómez",
    productos: [{ nombre: "Cerveza", cantidad: 3, precio: 12 }],
    ingresoJuego: 70,
    ingresoConsumos: 36,
    descuento: 0,
    total: 106,
    estado: "cerrada",
  },
  {
    id: "OP-024",
    fecha: getDate(20),
    tipo: "billar",
    mesa: "Mesa 1",
    tipoMesa: "billar",
    metodoPago: "transferencia",
    usuario: "Ana Martínez",
    productos: [
      { nombre: "Agua", cantidad: 3, precio: 4 },
      { nombre: "Hamburguesa", cantidad: 1, precio: 25 },
    ],
    ingresoJuego: 86,
    ingresoConsumos: 37,
    descuento: 0,
    total: 123,
    estado: "cerrada",
  },
  {
    id: "OP-025",
    fecha: getDate(25),
    tipo: "billar",
    mesa: "Mesa 3",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Juan Pérez",
    productos: [
      { nombre: "Nachos", cantidad: 3, precio: 25 },
      { nombre: "Coca Cola", cantidad: 2, precio: 8 },
    ],
    ingresoJuego: 94,
    ingresoConsumos: 91,
    descuento: 5,
    total: 180,
    estado: "cerrada",
  },
  {
    id: "OP-026",
    fecha: getDate(25),
    tipo: "solo-consumo",
    metodoPago: "tarjeta",
    usuario: "María López",
    productos: [{ nombre: "Cerveza", cantidad: 6, precio: 12 }],
    ingresoJuego: 0,
    ingresoConsumos: 72,
    descuento: 0,
    total: 72,
    estado: "cerrada",
  },
  {
    id: "OP-027",
    fecha: getDate(25),
    tipo: "juegos",
    mesa: "Mesa 7",
    tipoMesa: "juegos",
    metodoPago: "mixto",
    usuario: "Carlos Gómez",
    productos: [{ nombre: "Hamburguesa", cantidad: 2, precio: 25 }],
    ingresoJuego: 77,
    ingresoConsumos: 50,
    descuento: 7,
    total: 120,
    estado: "abierta",
  },
  {
    id: "OP-028",
    fecha: getDate(28),
    tipo: "billar",
    mesa: "Mesa 5",
    tipoMesa: "billar",
    metodoPago: "efectivo",
    usuario: "Ana Martínez",
    productos: [
      { nombre: "Coca Cola", cantidad: 4, precio: 8 },
      { nombre: "Agua", cantidad: 2, precio: 4 },
    ],
    ingresoJuego: 89,
    ingresoConsumos: 40,
    descuento: 0,
    total: 129,
    estado: "cerrada",
  },
  {
    id: "OP-029",
    fecha: getDate(28),
    tipo: "juegos",
    mesa: "Mesa 8",
    tipoMesa: "juegos",
    metodoPago: "tarjeta",
    usuario: "Juan Pérez",
    productos: [
      { nombre: "Cerveza", cantidad: 2, precio: 12 },
      { nombre: "Nachos", cantidad: 2, precio: 25 },
    ],
    ingresoJuego: 73,
    ingresoConsumos: 74,
    descuento: 0,
    total: 147,
    estado: "cerrada",
  },
  {
    id: "OP-030",
    fecha: getDate(28),
    tipo: "solo-consumo",
    metodoPago: "efectivo",
    usuario: "María López",
    productos: [{ nombre: "Hamburguesa", cantidad: 4, precio: 25 }],
    ingresoJuego: 0,
    ingresoConsumos: 100,
    descuento: 0,
    total: 100,
    estado: "cerrada",
  },
]

// Export the constant
export { OPERACIONES_FIXTAS }
