import type { CatalogState } from "./types"

// Seed data for catalogs
export const seedCatalogos: CatalogState = {
  productos: [
    {
      id: "prod-1",
      codigo: "BEB-001",
      nombre: "Coca Cola",
      categoria: "Bebidas",
      precio: 8,
      activo: true,
      afectaStock: true,
      stockActual: 50,
      stockMinimo: 10,
    },
    {
      id: "prod-2",
      codigo: "BEB-002",
      nombre: "Agua Pura",
      categoria: "Bebidas",
      precio: 5,
      activo: true,
      afectaStock: true,
      stockActual: 30,
      stockMinimo: 15,
    },
    {
      id: "prod-3",
      codigo: "SNK-001",
      nombre: "Papas Fritas",
      categoria: "Snacks",
      precio: 10,
      activo: true,
      afectaStock: true,
      stockActual: 25,
      stockMinimo: 10,
    },
    {
      id: "prod-4",
      codigo: "COM-001",
      nombre: "Hamburguesa",
      categoria: "Comida",
      precio: 25,
      activo: true,
      afectaStock: false,
    },
    {
      id: "prod-5",
      codigo: "COM-002",
      nombre: "Hot Dog",
      categoria: "Comida",
      precio: 15,
      activo: true,
      afectaStock: false,
    },
  ],
  reglasCobro: [
    {
      id: "regla-billar",
      tipo: "billar",
      duracionBloque: 30,
      precioBloque: 10,
      cobrarPrimerBloque: true,
      tolerancia: 10,
    },
    {
      id: "regla-juegos",
      tipo: "juegos",
      precioPorJugadorHora: 6,
    },
  ],
  metodosPago: [
    { id: "metodo-efectivo", nombre: "Efectivo", habilitado: true },
    { id: "metodo-tarjeta", nombre: "Tarjeta", habilitado: true },
    { id: "metodo-transferencia", nombre: "Transferencia", habilitado: true },
    { id: "metodo-mixto", nombre: "Mixto", habilitado: true },
  ],
  motivos: [
    {
      id: "motivo-corr-1",
      tipo: "correccion",
      descripcion: "Error en cantidad",
      activo: true,
    },
    {
      id: "motivo-corr-2",
      tipo: "correccion",
      descripcion: "Producto incorrecto",
      activo: true,
    },
    {
      id: "motivo-corr-3",
      tipo: "correccion",
      descripcion: "Cliente canceló",
      activo: true,
    },
    {
      id: "motivo-desc-1",
      tipo: "descuento",
      descripcion: "Cliente frecuente",
      activo: true,
    },
    {
      id: "motivo-desc-2",
      tipo: "descuento",
      descripcion: "Promoción especial",
      activo: true,
    },
  ],
  correlativo: {
    prefijo: "C-",
    longitud: 3,
    proximoNumero: 1,
  },
  identidad: {
    nombreComercial: "Billares Chapinlandia",
    moneda: "Q",
    textoContacto: "Tel: 2345-6789 | billares@chapinlandia.com",
  },
  usuarios: [
    {
      id: "user-admin-1",
      nombre: "Administrador",
      email: "admin@chapinlandia.com",
      rol: "admin",
      activo: true,
      fechaCreacion: new Date().toISOString(),
    },
  ],
  ajustesStock: [],
  bitacora: [],
  movimientosInventario: [],
}
